### ISSUE TITLE
Add NZBGeek

### ISSUE THREAD

**Issue by JSKershaw** [jparkerweb/NzbDrone_Xtender#17]
Would it be possible to add NZBGeek to the list of providers?

Links are: https://nzbgeek.info/
or for VIG: https://01100111011001010110010101101011.info/
Thanks for this great tool!

**Comment by jparkerweb** [comment]
URL for search criteria example:
https://nzbgeek.info/geekseek.php?browseincludewords=walking+dead+s03e06
